function ReportsFiltersBar({ copy, filters, options, onChange, onReset, onQuickExport }) {
  return (
    <div className="rptFilterBar">
      <div className="rptFilterGroup"><label className="rptFilterLabel" htmlFor="reports-date-from">{copy.rptFrom}</label><div className="rptDateField"><input id="reports-date-from" type="date" className="rptDateInput" value={filters.dateFrom} onChange={(e) => onChange("dateFrom", e.target.value)} /><span className="rptDateIcon" aria-hidden="true"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.7"><rect x="3.25" y="4.5" width="13.5" height="12.25" rx="2.25" /><path d="M6.5 2.75v3.5M13.5 2.75v3.5M3.25 8.25h13.5" /></svg></span></div></div>
      <div className="rptFilterGroup"><label className="rptFilterLabel" htmlFor="reports-date-to">{copy.rptTo}</label><div className="rptDateField"><input id="reports-date-to" type="date" className="rptDateInput" value={filters.dateTo} onChange={(e) => onChange("dateTo", e.target.value)} /><span className="rptDateIcon" aria-hidden="true"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.7"><rect x="3.25" y="4.5" width="13.5" height="12.25" rx="2.25" /><path d="M6.5 2.75v3.5M13.5 2.75v3.5M3.25 8.25h13.5" /></svg></span></div></div>
      <div className="rptFilterGroup"><label className="rptFilterLabel">{copy.rptBrand}</label><select className="rptSelect" value={filters.brand} onChange={(e) => onChange("brand", e.target.value)}><option value="all">{copy.insightsAllBrands}</option>{options.brands.map((value) => <option key={value} value={value}>{value}</option>)}</select></div>
      <div className="rptFilterGroup"><label className="rptFilterLabel">{copy.rptStatus}</label><select className="rptSelect" value={filters.status} onChange={(e) => onChange("status", e.target.value)}><option value="all">{copy.filterAllStatus}</option><option value="Open">{copy.filterOpen}</option><option value="In Progress">{copy.filterInProgress}</option><option value="Replied">{copy.filterReplied}</option><option value="Closed">{copy.filterClosed}</option></select></div>
      <div className="rptFilterGroup"><label className="rptFilterLabel">{copy.rptSource}</label><select className="rptSelect" value={filters.source} onChange={(e) => onChange("source", e.target.value)}><option value="all">{copy.rptAllSources}</option>{options.sources.map((value) => <option key={value} value={value}>{value}</option>)}</select></div>
      <div className="rptFilterGroup"><label className="rptFilterLabel">{copy.rptPriority}</label><select className="rptSelect" value={filters.priority} onChange={(e) => onChange("priority", e.target.value)}><option value="all">{copy.filterAllPriority}</option><option value="High">{copy.filterHigh}</option><option value="Medium">{copy.filterMedium}</option><option value="Low">{copy.filterLow}</option></select></div>
      <div className="rptFilterGroup"><label className="rptFilterLabel">{copy.rptSla}</label><select className="rptSelect" value={filters.slaStatus} onChange={(e) => onChange("slaStatus", e.target.value)}><option value="all">{copy.rptAllSla}</option><option value="pending">Pending</option><option value="at_risk">At Risk</option><option value="breached">Breached</option></select></div>
      <div className="rptFilterGroup"><label className="rptFilterLabel">{copy.rptCategory}</label><select className="rptSelect" value={filters.category} onChange={(e) => onChange("category", e.target.value)}><option value="all">{copy.rptAllCategories}</option>{options.categories.map((value) => <option key={value} value={value}>{value}</option>)}</select></div>
      <div className="rptFilterGroup"><label className="rptFilterLabel">{copy.rptBranch}</label><select className="rptSelect" value={filters.branch} onChange={(e) => onChange("branch", e.target.value)}><option value="all">{copy.insightsAllBranches}</option>{options.branches.map((value) => <option key={value} value={value}>{value}</option>)}</select></div>
      <button type="button" className="ghost-btn" onClick={onReset}>↺ {copy.dashboardReset}</button>
      <button type="button" className="ghost-btn" onClick={onQuickExport}>⬇ {copy.export}</button>
    </div>
  );
}

export default ReportsFiltersBar;
